### ISSUE TITLE
Conflicting Servo ID info for wx250s

### ISSUE THREAD

**Issue by aaronjenson** [TrossenRobotics/interbotix_xsarms_docs#4]
In [docs/specifications/wx250s.rst](https://github.com/TrossenRobotics/interbotix_xsarms_docs/blob/main/docs/specifications/wx250s.rst), the Default Joint Limits table lists forearm roll as servo ID 7, while in the Default Servo Configurations (found in: [docs/_data/servos_wx250s.csv](https://github.com/TrossenRobotics/interbotix_xsarms_docs/blob/main/docs/_data/servos_wx250s.csv)), forearm roll is servo ID 6.

**Comment by lukeschmitt-tr** [comment]
The default servo config table is correct. forearm_roll is ID 6 and wrist_angle is ID 7. See the [wx250s motor config file](https://github.com/Interbotix/interbotix_ros_manipulators/blob/main/interbotix_ros_xsarms/interbotix_xsarm_control/config/wx250s.yaml) for details.

Thanks for catching this. Happy to accept a PR to fix it.
